apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: team-pod
  namespace: default
spec:
  containers:
  - args:
    - sleep
    - "4800"
    image: busybox
    name: pod
    envFrom:
    - configMapRef:
        name: users-cm

    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
